### ISSUE TITLE
Kernel matrices generated by GaKCo are not symmetric

### ISSUE THREAD

**Issue by kiramt** [QData/GaKCo-SVM#8] opened 2018-05-18 14:11 UTC
Kernel matrices, by definition, should be symmetric. However GaKCo seems to produce matrices which are not symmetric. E.g. try:

`$ ./GaKCo -g 10 -k 8 temp.fasta dict.txt labels.txt kernels.txt`

where temp.fasta is:
```
>1
ACGACGTGACGACCCGATAGATG
>0
AGTCCCAAATCCGTAAAAGACGA
```

and dict.txt is:
```
A
C
G
T

```

The kernel produced is:
```
1:1.000000e+00 2:9.235347e-03 
1:1.108242e-02 2:1.000000e+00
```

**Comment by rs3zz** [comment] 2018-05-18 15:25
That is strange. I think some of the recent changes might have introduced some unintentional bugs. 
I would like to point you to our updated GaKCo tool : https://github.com/QData/iGakco-SVM

It has much smoother training and testing as well as option to generate kernels. 
Please let us know if that works as intended, while we try to fix the issues reported here. Thanks.

**Comment by dblakely** [comment] 2018-05-18 17:37
I'm currently working on this and will let you guys know when I have it fixed.

**Comment by kiramt** [comment] 2018-05-21 08:50
Thanks - I had a look at iGaKCo. Happily, it is producing symmetric kernel matrices, but it is also core dumping in some cases. I'll log an issue on the iGaKCo page.

**Comment by dblakely** [comment] 2018-07-10 14:39
I pushed a fix for this. I only observed the issue with small datasets like the one you provided, but the issue looks like it's now fixed for those cases. Thanks for pointing this out. Definitely let us know if find any other problems.

**Closed as completed by dblakely** 2018-07-10 14:39 UTC
